POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJha2kiLCJpZCI6IjY0OGZlNTM5YjcwOTJkNDI3MzNlMWEzOSIsImlhdCI6MTY4NzIwNzMyMiwiZXhwIjoxNjg3MjEwOTIyfQ.pa4NNQGU6TBBNw0vn8xzIZ9BL-JZ-xxmpCXthh_BObA

{
  "title": "TestToken4",
  "author": "TestToken4",
  "url": "www.testtoken4.com",
  "likes": 60,
  "userId": "648fe539b7092d42733e1a39"
}